### ISSUE TITLE
Python 2.6's ET doesn't have xml_declaration=True

### ISSUE THREAD

**Issue by coofercat** [dylanahsmith/errbit-reporter-python#1]
I'm trying to use errbit_reporter on a Centos 6 box, which has Python 2.6 installed. It's failing to send anything to Errbit because of this line:

```
ET.ElementTree(root).write(
            buffer, encoding='utf-8', xml_declaration=True)
```

Here's the full backtrace I get:

```
  File "/tmp/errbit_send.py", line 93, in <module>
    notice_metadata = client.notify(**request)
  File "/usr/lib/python2.6/site-packages/errbit_reporter/client.py", line 91, in notify
    return self.send_notice(notice, timeout=timeout)
  File "/usr/lib/python2.6/site-packages/errbit_reporter/client.py", line 106, in send_notice
    request = urllib.request.Request(url, notice.serialize())
  File "/usr/lib/python2.6/site-packages/errbit_reporter/notice.py", line 111, in serialize
    buffer, encoding='utf-8', xml_declaration=True)
TypeError: write() got an unexpected keyword argument 'xml_declaration'
```

It turns out that ElementTree doesn't have the xml_declaration argument in Python 2.6 (source: http://stackoverflow.com/a/12457501/917444). The SO comments suggest using lxml instead, which presumably would also work in later Python versions and installs.

It's also possible to make this work with Python 2.6 by patching the notice.py file with this:

```
    try:
        ET.ElementTree(root).write(
            buffer, encoding='utf-8', xml_declaration=True)
    except TypeError:
        ET.ElementTree(root).write(buffer, encoding='utf-8')
```

...although this is probably a bit too cheesy to be an acceptable permanent solution ;-)

**Comment by siloam** [comment]
`...although` this is probably a bit too cheesy to be an acceptable permanent solution ;-)

It could not be acceptable as permanent soultuion. The declaration is still not present!
4 years after, Python 3.7... No changes in the docs.
Unacceptable!

Ok, they fixed this in Python 3.8.
